language: node_js
node_js:
- '0.10'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
- '12'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

matrix:
  include:
    - os: linux
      dist: xenial

    - os: linux
      dist: xenial
      arch: arm64
      node_js: 10

    - os: osx
      osx_image: xcode11.0
      node_js: 10

install: skip

script:
  - npm install node-gyp
  - npm install --loglevel verbose

deploy:
  provider: npm
  email: zone117x@gmail.com
  api_key:
    secure: D9lpUDAx1OudPBji3mapnAhOug3wcEBqFrNgWaFh5XiYesa/f/X0gMOJggLlvzyhLHKs8VdTHShdu3XzlC3EDwr5wCdgYO1JSOyDo93FG7Y/qhPDVFnzdtsKmr813Qtj2UDKIh2ZP+JnjKaITrvUwRmdi/8+B9Enr5o9ulFb/a0=